-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(ONLINE_SALE_ID) AS CNT
        FROM ONLINE_SALE
        GROUP BY USER_ID, PRODUCT_ID) AS T1
WHERE T1.CNT > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC;