-- 코드를 입력하세요
SELECT T1.FLAVOR 
FROM FIRST_HALF AS T1
LEFT JOIN ICECREAM_INFO AS T2
    ON T1.FLAVOR = T2.FLAVOR
WHERE TOTAL_ORDER > 3000
    AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;