-- 코드를 입력하세요
SELECT TITLE, T1.BOARD_ID, REPLY_ID, T2.WRITER_ID, T2.CONTENTS, DATE_FORMAT(T2.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM (SELECT *
        FROM USED_GOODS_BOARD
        WHERE SUBSTR(CREATED_DATE, 1, 7) = '2022-10') AS T1
JOIN USED_GOODS_REPLY AS T2
    ON T1.BOARD_ID = T2.BOARD_ID
ORDER BY T2.CREATED_DATE, TITLE;