-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(PRODUCT_ID) AS PRODUCT_CNT
        FROM ONLINE_SALE
        GROUP BY USER_ID, PRODUCT_ID) AS T1
WHERE T1.PRODUCT_CNT > 1
ORDER BY USER_ID, PRODUCT_ID DESC;