-- 코드를 작성해주세요
WITH FISH_MAX_LEN AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT ID, FISH_NAME, T1.LENGTH
FROM FISH_MAX_LEN AS T1
LEFT JOIN FISH_INFO AS T2
    ON (T1.FISH_TYPE = T2.FISH_TYPE) AND (T1.LENGTH = T2.LENGTH)
LEFT JOIN FISH_NAME_INFO AS T3
    ON T1.FISH_TYPE = T3.FISH_TYPE
ORDER BY ID;